// import './example/index'
// import './Ch04/02-lifecycle'
// import './Ch04/03-Ajax'
// import './react-router-example/index'
// import './react-router-example2/index'
// import './react-flux-example/index'
// import './redux-example/index'
// import './redux-example2/index'
import './react-redux-example/index'