// import './components/1-jsx'
// import './components/2-component'
// import './components/3-state'
// import './practice/2-children'
// import './practice/3-controlled-components'
// import './practice/4-default-props'
import './practice/5-prop-type'